# Generated by Django 4.0.1 on 2022-06-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
