# Generated by Django 4.0.1 on 2022-07-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_whitelist_alter_botmanager_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelist',
            old_name='upload',
            new_name='file',
        ),
    ]
