# Generated by Django 4.0.1 on 2022-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_upload_whitelist_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tax_collected', models.CharField(max_length=255)),
                ('current_total_balance', models.CharField(max_length=255)),
                ('total_deposit_amount', models.CharField(max_length=255)),
                ('transaction_list', models.CharField(max_length=255)),
            ],
        ),
    ]
